# SPDX-FileCopyrightText: 2026 Paweł Biernacki
# SPDX-License-Identifier: MIT

class IRCError(Exception): ...
class IRCConnectionError(IRCError): ...
class IRCParseError(IRCError): ...
class IRCAuthenticationError(IRCError): ...

class IRCHandlerError(IRCError):
    errors: list[BaseException]
    def __init__(self, errors: list[BaseException]) -> None: ...
