# SPDX-FileCopyrightText: 2026 Paweł Biernacki
# SPDX-License-Identifier: MIT

class IRCError(Exception): ...
class IRCConnectionError(IRCError): ...
class IRCParseError(IRCError): ...
class IRCAuthenticationError(IRCError): ...
