# SPDX-FileCopyrightText: 2026 Paweł Biernacki
# SPDX-License-Identifier: MIT

from dataclasses import dataclass

@dataclass
class Message:
    command: str
    params: list[str] = ...
    prefix: str | None = ...
    tags: dict[str, str] = ...

    @classmethod
    def parse(cls, raw: str) -> Message: ...
    def __str__(self) -> str: ...
